### ISSUE TITLE
[Unit test failure] Module symbol is not re-imported if the corresponding library is re-imported with `dy_import_module_symbols`

### ISSUE THREAD

**Issue by vladimir-v-diaz** [SeattleTestbed/seattlelib_v2#156] opened 2014-12-19 16:25 UTC
Testing on Linux

```Bash
$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

```Bash
$ python utf.py -f ut_seattlelib_dylinkrepyportabilityimportmodulesymbols.py
Testing module: seattlelib
	Running: ut_seattlelib_dylinkrepyportabilityimportmodulesymbols.py [ FAIL ]
--------------------------------------------------------------------------------
Standard out :
..............................Produced..............................
Unexpected contents in variable: local override (expected examplelib-repy.r2py's foo)

..............................Expected..............................
None
--------------------------------------------------------------------------------
$ 
```

The test case that is failing:
https://github.com/SeattleTestbed/seattlelib_v2/blob/master/tests/ut_seattlelib_dylinkrepyportabilityimportmodulesymbols.py#L19-L21

The commit that introduced this unit test, and the test case that fails:
https://github.com/SeattleTestbed/seattlelib_v2/commit/e33ffa8d7a54063fddb782c896d3877173eecd55

**Comment by aaaaalbert** [comment] 2015-02-05 15:41
See SeattleTestbed/portability#27. This test (and compaions) was made to demonstrate a current shortcoming (i.e. `dy_import_module_symbols` does not work correctly) versus the way Python handles these issues, so that we are gently reminded to fix this behavior.

However, the functionality is seldom used (if at all), limiting the repercussions of the problem.

**Comment by vladimir-v-diaz** [comment] 2015-02-05 15:55
I did not know that this was a known limitation of `dy_import_module_symbols()` (sorry about that, I should have asked).  I will add a NOTE or TODO to the comment [here](https://github.com/SeattleTestbed/seattlelib_v2/blob/master/tests/ut_seattlelib_dylinkrepyportabilityimportmodulesymbols.py#L19), and in companion modules, so it's clear that this test condition is currently expected to fail.

**Comment by aaaaalbert** [comment] 2015-02-05 19:11
Apologies, I should have thought about adding a note myself.

Re why it was hard to find this information in the first place: The tests were committed to SVN "back in the days", and it looks like linking between the issues (ported to GitHub) and commits (SVN `r`+number vs Git hash) leaves something to be desired.

**Comment by aaaaalbert** [comment] 2016-08-26 16:07
The problem is not yet solved, but moved to the appropriate place now: SeattleTestbed/portability@dc680699be2b02a56b56c10c782799efd8ae7e57, and also has an issue there, SeattleTestbed/portability#27. Thanks!

**Closed by aaaaalbert** 2016-08-26 16:07 UTC
Labels: bug
